### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by fanyuzeng** [UIA-CAIR/gym-maze#4]
pip install git+https://github.com/cair/gym-maze.git
**I install gym-maze successfully. However, when I run the "Basic Usage" example, the error appears as following:**
Traceback (most recent call last):
  File "/home/cr/pycharmProjects/0Test/test.py", line 3, in <module>
    import gym_maze  # This is required in order to load gym-maze
  File "/usr/local/lib/python2.7/dist-packages/gym_maze/__init__.py", line 32
    cls_constructor = make_constructor(args=(*size, state, mechanic, mechanic_arg))
                                             ^
SyntaxError: invalid syntax

**when I change project interpreter from python2 to python3, this error disappear, but new error appear:**
Traceback (most recent call last):
  File "/home/cr/pycharmProjects/0Test/test.py", line 3, in <module>
    import gym_maze  # This is required in order to load gym-maze
ImportError: No module named 'gym_maze'

**How can I resolve this error?**

**Comment by perara** [comment]
Try using python 3 :)

**Comment by fanyuzeng** [comment]
I have tried **pip3 install git+https://github.com/cair/gym-maze.git** and **sudo pip3 install git+https://github.com/cair/gym-maze.git** yesterday. However, some errors remain exist:

Downloading/unpacking git+https://github.com/cair/gym-maze.git
  Cloning https://github.com/cair/gym-maze.git to /tmp/pip-ekp0sldv-build
  Running setup.py (path:/tmp/pip-ekp0sldv-build/setup.py) egg_info for package from git+https://github.com/cair/gym-maze.git
Requirement already satisfied (use --upgrade to upgrade): gym in ./gym (from gym-maze==2.0.0)
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python3.4/dist-packages (from gym-maze==2.0.0)
Downloading/unpacking pygame (from gym-maze==2.0.0)
  Downloading pygame-1.9.4.tar.gz (4.8MB): 4.8MB downloaded
  Running setup.py (path:/tmp/pip_build_cr/pygame/setup.py) egg_info for package pygame
    
    
    WARNING, No "Setup" File Exists, Running "config.py"
    Using UNIX configuration...
    
    
    Hunting dependencies...
    WARNING: "pkg-config freetype2" failed!
    SDL     : found 1.2.15
    FONT    : found
    IMAGE   : found
    MIXER   : not found
    PNG     : found
    JPEG    : found
    SCRAP   : found
    PORTMIDI: not found
    PORTTIME: not found
    FREETYPE: found 2.5.2
    Missing dependencies
    Complete output from command python setup.py egg_info:
    



WARNING, No "Setup" File Exists, Running "config.py"

Using UNIX configuration...





Hunting dependencies...

WARNING: "pkg-config freetype2" failed!

SDL     : found 1.2.15

FONT    : found

IMAGE   : found

MIXER   : not found

PNG     : found

JPEG    : found

SCRAP   : found

PORTMIDI: not found

PORTTIME: not found

FREETYPE: found 2.5.2

Missing dependencies

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_cr/pygame
Storing debug log for failure in /home/cr/.pip/pip.log

**Comment by perara** [comment]
The issues seems to be with pygame, which is a dependency and not the deep-maze environment itself. What you could do is to download the source files (This git) and just add the directory to your project.
I just tested it myself on arch-linux without any issues. (Python 3.7, however, gym-maze was developed on Ubuntu 17.10 )

**Comment by fanyuzeng** [comment]
Thank you so much. I reinstall some dependence  and upgrade my ubuntu14.04 to 16.04. Finally, the issue is resolved.
